displayName=Runesky Video Player
author=ixl911ixl
description=Displays user-supplied local media as a configurable runelite overlay    
tags= video, overlay, picture in picture, pip, ambience, media, skybox, 
version= 1
plugins=com.runesky.RuneskyVideoPlugin
build=standard